spring:
  application:
    name: gateway-service
    
info:
  component: Edge Server
  
#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false

zuul:
#  prefix: /api
  routes:
    authentication: 
      path: /auth/**
      serviceId: auth-service
#hystrix.command.default.execution.timeout.enabled
#ribbon:
#  eureka:
#    enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
